-- Soda Hotel schema for Neon PostgreSQL.
-- Run this file in the Neon SQL Editor against your project's database.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (status IN ('user', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS room (
  roomid VARCHAR(50) PRIMARY KEY,
  floor VARCHAR(20) NOT NULL,
  roomstyle VARCHAR(100) NOT NULL,
  roomdetail TEXT,
  price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
  countroom INTEGER NOT NULL DEFAULT 0 CHECK (countroom >= 0),
  countuser INTEGER NOT NULL DEFAULT 1 CHECK (countuser > 0),
  star NUMERIC(2,1) DEFAULT 0 CHECK (star >= 0 AND star <= 5),
  picture VARCHAR(500),
  name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  bookingid VARCHAR(64) PRIMARY KEY,
  username VARCHAR(100) NOT NULL REFERENCES users(username) ON UPDATE CASCADE,
  bookingdate DATE NOT NULL,
  checkin DATE NOT NULL,
  checkout DATE NOT NULL,
  countroom INTEGER NOT NULL CHECK (countroom > 0),
  roomid VARCHAR(50) NOT NULL REFERENCES room(roomid),
  phone VARCHAR(30) NOT NULL,
  totalprice NUMERIC(12,2) NOT NULL CHECK (totalprice >= 0),
  payment VARCHAR(50) NOT NULL,
  paymentstatus VARCHAR(50) NOT NULL DEFAULT 'Unpaid',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (checkout > checkin)
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(username);
CREATE INDEX IF NOT EXISTS idx_orders_dates ON orders(checkin, checkout);
CREATE INDEX IF NOT EXISTS idx_orders_room_dates ON orders(roomid, checkin, checkout);
CREATE INDEX IF NOT EXISTS idx_room_style ON room(roomstyle);

-- Optional first admin account:
-- Create a normal account through the website, then run:
-- UPDATE users SET status = 'admin' WHERE username = 'YOUR_USERNAME';
